### ISSUE TITLE
It eats the closing `)` in comments in source files

### ISSUE THREAD

**Issue by tunnckoCore** [OctoLinker/browser-extension#203]
For example, you have `index.js` with

```js
// let foo = require('foo-bar')
```

When reviewing the file from github there's no closing `)`.

**BUT**, it might be just fixed in 4.5, not sure. Or it may be only in some cases. I will be lookin on that and report back.

**Comment by josephfrazier** [comment]
As you mentioned in your edit, this should be fixed in 4.5 (specifically https://github.com/OctoLinker/browser-extension/commit/ad7f88276475320887bc218c1cd59a1931ebc141), which was just recently released. Therefore, I'm going to go ahead and close this, but please do report back if you find that the fix was incomplete :-)

**Comment by tunnckoCore** [comment]
Great. I was thinking to create an issue before few months, but don't have the time, and when now it pops up that it has new version I said to myself "oo okey, i report my problem", haha. But while writing the issue, navigate to some of my projects and didn't seen the problem, so.. Yea.

Probably you right. And yea, I'll report if something is wrong/incomplete.
