### ISSUE TITLE
Bug in require regex

### ISSUE THREAD

**Issue by tunnckoCore** [OctoLinker/browser-extension#236]
It seems it fails to detect when there is spaces between parens and the string literal

something like

```js
var rollup = require( 'rollup' )
```

Not sure.

~~https://github.com/jonschlinkert/requires-regex may help~~ actually it not helps for that case

**Comment by josephfrazier** [comment]
Thanks for the report! The relevant regex is located [here](https://github.com/OctoLinker/browser-extension/blob/beec18f5baf8bf9d5fba806b6e8a6b3caa0da692/packages/helper-grammar-regex-collection/index.js#L1), and should need only small changes to get this working. However, its tests actually ensure that the following *isn't* matched (see the top/bottom lines highlighted [here](https://github.com/OctoLinker/browser-extension/blob/beec18f5baf8bf9d5fba806b6e8a6b3caa0da692/packages/helper-grammar-regex-collection/test.js#L76-L83)), so that will need to be changed:

```js
var rollup = require( 'rollup' )
```

Would you be interested in submitting a pull request that fixes this?  [CONTRIBUTING.md](https://github.com/OctoLinker/browser-extension/blob/master/CONTRIBUTING.md) has a development guide, and I'd be happy to help with any issues you encounter.

**Comment by tunnckoCore** [comment]
Yea, I can come with PRs soon, seen these things are easy fixes. To not repeat, answer is the same for #235 too :)

**Comment by josephfrazier** [comment]
Awesome, I look forward to seeing the PRs!

**Comment by Arkni** [comment]
Hi!
Any update regarding this issue ?

**Comment by tunnckoCore** [comment]
I'm busy, but PR would be easy. :)

**Comment by Arkni** [comment]
I think the only changes that needs to be done are:
```diff
 packages/helper-grammar-regex-collection/index.js | 2 +-
 packages/helper-grammar-regex-collection/test.js  | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/packages/helper-grammar-regex-collection/index.js b/packages/helper-grammar-regex-collection/index.js
index f0c6cb6..23d42ea 100644
--- a/packages/helper-grammar-regex-collection/index.js
+++ b/packages/helper-grammar-regex-collection/index.js
@@ -1,6 +1,6 @@
 import go from './go.js';

-const REQUIRE = /require(?:\.resolve)?(?:\s|\()['"]([^'"\s]+)['"]\)?/g;
+const REQUIRE = /require(?:\.resolve)?(?:\s|\( ?)['"]([^'"\s]+)['"] ?\)?/g;
 const IMPORT = /import [\r\n\s\w{},*\$]*(?: from )?['"]([^'"\s]+)['"]/g;
 const EXPORT = /export [\r\n\s\w{},*\$]*(?: from )['"]([^'"\s]+)['"]/g;
 const GEM = /gem ['"]([^'"\s]+)['"]/g;
diff --git a/packages/helper-grammar-regex-collection/test.js b/packages/helper-grammar-regex-collection/test.js
index 467e97b..b078c7c 100644
--- a/packages/helper-grammar-regex-collection/test.js
+++ b/packages/helper-grammar-regex-collection/test.js
@@ -48,6 +48,7 @@ const fixtures = {
   REQUIRE: {
     valid: [
       'require("foo")',
+      'require( "foo" )',
       'var foo = require("foo")',
       'var $ = require("foo")',
       'var _ = require("foo")',
@@ -65,6 +66,7 @@ const fixtures = {
       // require.resolve
       'require.resolve "foo"',
       'require.resolve("foo")',
+      'require.resolve( "foo" )',
       'var foo = require.resolve("foo")',
       ['var foo = require.resolve("foo")var bar = require.resolve("bar")', ['foo', 'bar']],
     ],
@@ -73,14 +75,12 @@ const fixtures = {
       'require"foo"',
       'require ("foo")',
       'require (foo)',
-      'require( "foo" )',
       'require("fo o")',
       // require.resolve
       'require.resolve(foo)',
       'require.resolve"foo"',
       'require.resolve ("foo")',
       'require.resolve (foo)',
-      'require.resolve( "foo" )',
       'require.resolve("fo o")',
       'requireDresolve("foo")',
     ],
```

Is that right?

**Comment by josephfrazier** [comment]
That looks pretty good, @Arkni! Would you like to open a pull request with the changes? I think we should also adjust the regex and tests to allow any amount of whitespace around the quotes.

**Comment by Arkni** [comment]
See #281
