### ISSUE TITLE
Doesn't work for go packages on Firefox

### ISSUE THREAD

**Issue by momoneko** [OctoLinker/browser-extension#275]
Hi. The extension does not work for go imports on Firefox. Tested on Mac OS X and Ubuntu.

**Comment by josephfrazier** [comment]
Hi @momoneko, can you provide some more information about your testing? Specifically, which version of Firefox are you using, and on what page does the extension not work? For example, the imports shown here work correctly for me in Firefox 51.0.1 (64-bit):

https://github.com/golang/go/blob/329fff0db01dd1252444cf106dffe72ba20ddbc8/src/archive/tar/common.go#L16

**Comment by momoneko** [comment]
On both Mac and Ubuntu it's 51.0.1 (64-bit). I installed it from the Mozilla Store. OctoLinker is at version 4.7.1. 

It doesn't work on the page you linked to, Mac and Ubuntu alike. It does work for Python.

**Comment by josephfrazier** [comment]
Oh, that's because the latest version (4.8.0, which is the first to include Go support) was released only 2 days ago, and hasn't yet been approved for release by the folks at the Mozilla Store. I don't know how long it typically takes them to review the release, but the extension is currently at position 66 in the review queue.

**Comment by stefanbuck** [comment]
There is not much progress. It's now on position 48 😞

**Comment by momoneko** [comment]
Is there any place where I could keep track of it? Or it's limited to owners/contributors?

**Comment by stefanbuck** [comment]
Nope, it's only visible to us. I'll keep you updated.

**Comment by stefanbuck** [comment]
4.8.0 is now available
