### ISSUE TITLE
Can't resolve path contain dot

### ISSUE THREAD

**Issue by CatTail** [OctoLinker/browser-extension#56]
[This line](https://github.com/rackt/redux/blob/ca6ded66484d4d73134ee1bc7bb3c205e42165a4/examples/real-world/containers/Root.js#L2) use `require('./Root.prod')` to load module, linker can't properly resolve module path.

**Comment by stefanbuck** [comment]
Mhh that's an edge case, because I use `path.extname` to determine if there is a file extension present. I'll have a look on it later this week. If you are interested in sending a fix, this would be the right place to start debugging it. https://github.com/octo-linker/core/blob/e970d1c655c6bb82d953c6679c6ac316338f72c2/lib/live-resolver/index.js#L87

**Comment by stefanbuck** [comment]
Fixed by @josephfrazier with https://github.com/OctoLinker/browser-extension/issues/271
