### ISSUE TITLE
Doesn't work in conjunction with github-highlight-selected Chrome extension

### ISSUE THREAD

**Issue by dannyfritz** [OctoLinker/browser-extension#88]
It fails to redirect when `github-highlight-selected` is also installed https://github.com/Nuclides/github-highlight-selected

![atom_2016-05-27_08-44-13](https://cloud.githubusercontent.com/assets/315788/15611349/34495ee0-23e7-11e6-9686-242663349ac0.png)

Reason the bug is opened here instead of there is because the other extension works, but breaks this one. If you feel it is a problem on their end, tell me to open an issue there or open one with more specific details.

**Comment by stefanbuck** [comment]
Thanks for filling this issue. The `github-highlight-selected` extension wraps every single word with a `<spam>` which cause this issue. Luckily the fix is quite simple on this end 😉 Updating the target source from `event.target` to `event.currentTarget` in the [click-handler](https://github.com/OctoLinker/browser-extension/blob/40cc8a5533e827361f42058731886b6c210f1d0a/lib/click-handler.js#L39) should fix this issue. Would you like to write a patch for this?

**Comment by dannyfritz** [comment]
Yep, I can do a pull request sometime this weekend. :+1:

**Comment by stefanbuck** [comment]
Will be fixed with the next release
